[profile.default]
src = "."
out = "out"
libs = ["lib"]
remappings = ["forge-std/=lib/forge-std/src/"]

# This folder is used purely for computing canonical test vectors
# from the Rust side during `cargo test`.